(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.s1_goc = function() {
	this.initialize(img.s1_goc);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,104,36);


(lib.s1_khungphone = function() {
	this.initialize(img.s1_khungphone);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1012,492);


(lib.s1_ui = function() {
	this.initialize(img.s1_ui);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1300,632);


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.s1_ui();
	this.instance.setTransform(-650,-316);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-650,-316,1300,632);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.s1_ui();
	this.instance.setTransform(-650,-316);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-650,-316,1300,632);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1_copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AXPDBQgNgCgMgFQgLgGgIgHIANgVQAKAJAPAGQAPAFARAAQAaAAAMgMQANgMAAgaIAAgMQgKAMgOAFQgOAHgQAAQgVgBgRgJQgRgJgKgQQgKgQAAgVQAAgWAKgQQAKgQARgIQARgJAVAAQARAAAOAGQAPAFAJAMIAAgWIAaAAIAAB/QAAAogUASQgTATgmAAQgOgBgNgCgAXPATQgMAHgGAKQgHALAAAPQAAAOAHALQAGAKAMAHQALAGAPAAQAPAAAMgGQALgHAHgKQAGgLAAgOQAAgPgGgLQgHgKgLgHQgMgFgPAAQgPAAgLAFgAkBDBQgNgCgMgFQgLgGgIgHIANgVQAKAJAPAGQAPAFARAAQAaAAAMgMQANgMAAgaIAAgMQgKAMgOAFQgOAHgQAAQgVgBgRgJQgRgJgKgQQgKgQAAgVQAAgWAKgQQAKgQARgIQARgJAVAAQARAAAOAGQAPAFAJAMIAAgWIAaAAIAAB/QAAAogUASQgTATgmAAQgOgBgNgCgAkBATQgMAHgGAKQgHALAAAPQAAAOAHALQAGAKAMAHQALAGAPAAQAPAAAMgGQALgHAHgKQAGgLAAgOQAAgPgGgLQgHgKgLgHQgMgFgPAAQgPAAgLAFgARuC+QgFgDAAgHQAAgGAFgEQADgEAHAAQAGAAAEAEQAEAEAAAGQAAAHgEADQgEAEgGABQgHgBgDgEgEAgVACCQgWgOgMgaQgMgZgBgmQABgkAMgaQAMgaAWgNQAWgOAbAAQAcAAAWAOQAVANANAaQAMAaAAAkQAAAmgMAZQgNAagVAOQgWAOgcAAQgbAAgWgOgEAhmABSQAMgQAAgnQAAglgMgRQgMgRgUAAQgTAAgMARQgMARAAAlQAAAnAMAQQAMASATgBQAUABAMgSgA2tCAQgXgMgNgXQgOgWAAgdQAAgeAOgVQANgXAYgNQAXgMAegBQAXAAATAIQATAHAOAQIgTARQgLgMgOgFQgOgGgQAAQgWAAgRAKQgSAKgKAPQgKASAAAWQAAAVAKARQAKASASAJQARAKAWAAQAQAAAOgGQAOgGALgMIATASQgOAPgTAIQgTAIgXAAQgegBgYgNgARQCEQgRgLgKgQQgKgSAAgWQAAgWAKgRQAKgRARgJQARgJAXAAQAWAAASAJQARAJAKARQAKARAAAWQAAAWgKASQgKAQgRALQgSAJgWAAQgXAAgRgJgAReATQgLAHgHAMQgGAMAAAPQAAARAGALQAHALALAHQALAGAPAAQAOAAALgGQAMgHAGgLQAHgLAAgRQAAgPgHgMQgGgMgMgHQgLgFgOAAQgPAAgLAFgALZCGQgOgHgIgOQgIgPAAgVIAAhVIAbAAIAABRQAAAWAKALQALALATAAQAVAAAMgMQAMgNABgYIAAhMIAbAAIAACUIgaAAIAAgXQgIALgNAHQgNAGgQAAQgUAAgOgHgAIpCEQgSgLgKgQQgKgSAAgWQAAgVAKgSQAJgQARgKQARgJAWAAQAVAAARAJQAQAJAJARQAKASAAAWIAAAEIgBAEIh4AAQADAUAOAMQAOAMAXgBQANAAAKgDQALgGAIgJIAPASQgKAMgPAGQgPAGgSAAQgYAAgSgJgAJ9A3QgCgTgNgLQgNgMgTgBQgUABgNALQgNAMgCATIBfAAIAAAAgAFJCLQgMgCgKgEQgJgFgHgEIAMgWQAJAHAOAFQAOAEAPAAQASAAAJgFQAIgGAAgJQAAgIgHgEQgHgFgKgBIgXgFQgMgCgKgDQgLgFgHgIQgGgIgBgPQABgUAQgMQAQgLAdAAIAUABQAKACAJADQAJADAGADIgLAWQgKgHgLgCQgLgDgLAAQgSAAgIAFQgJAGAAAJQAAAIAHAFQAHAFAKACIAXADQAMACAKAFQALAEAHAIQAHAIAAAPQAAATgRAMQgRAMgeAAQgNAAgLgCgABjCEQgSgLgKgQQgKgSAAgWQAAgWAKgRQAKgRASgJQARgJAXAAQAVAAAPAIQAQAHAJAPIgVAOQgHgMgKgFQgLgEgMAAQgPAAgLAFQgMAHgGAMQgHAMAAAPQAAARAHALQAGAMAMAGQALAGAPAAQAMAAALgEQAKgGAHgKIAVAMQgJAQgQAIQgPAIgVAAQgXAAgRgJgAhPCEQgRgLgKgQQgKgSAAgWQAAgWAKgRQAKgRARgJQASgJAWAAQAXAAAQAJQARAJAKARQAKARAAAWQAAAWgKASQgKAQgRALQgQAJgXAAQgWAAgSgJgAhAATQgMAHgGAMQgHAMAAAPQAAARAHALQAGALAMAHQALAGAOAAQAPAAALgGQALgHAGgLQAGgLAAgRQAAgPgGgMQgGgMgLgHQgLgFgPAAQgOAAgLAFgAoXCBQgPgMAAgTQAAgNAGgKQAGgJANgGQANgFAWgBIAqAAIAAgFQAAgRgJgJQgKgKgUAAQgOAAgMAEQgNAEgIAIIgMgUQAMgJAQgFQAQgEASAAQAeAAARAOQAQAPAAAeIAABaIgZAAIAAgUQgHAKgMAFQgMAGgSAAQgZAAgPgMgAn+BNQgHADgDAFQgDAFAAAHQAAALAJAGQAIAGAQAAQAPAAALgGQALgHAFgNIAAgVIgpAAQgNAAgIAEgAshCEQgSgLgJgQQgKgSAAgWQAAgVAJgSQAKgQARgKQAQgJAWAAQAWAAAQAJQAQAJAKARQAJASAAAWIAAAEIAAAEIh5AAQADAUAPAMQAOAMAWgBQANAAALgDQALgGAIgJIAPASQgKAMgPAGQgPAGgTAAQgYAAgSgJgArMA3QgDgTgMgLQgNgMgUgBQgUABgMALQgNAMgDATIBgAAIAAAAgA0FCBQgPgMAAgTQAAgNAGgKQAGgJANgGQANgFAWgBIAqAAIAAgFQAAgRgJgJQgKgKgUAAQgOAAgMAEQgNAEgIAIIgMgUQAMgJAQgFQAQgEASAAQAeAAARAOQAQAPAAAeIAABaIgZAAIAAgUQgHAKgMAFQgMAGgSAAQgZAAgPgMgAzsBNQgHADgDAFQgDAFAAAHQAAALAJAGQAIAGAQAAQAPAAALgGQALgHAFgNIAAgVIgpAAQgNAAgIAEgAcnCMIAAgiIBXhRQAJgKAGgHQAFgIACgFIABgLQAAgOgJgGQgJgIgSAAQgOAAgMAGQgMAFgIAMIgmgYQANgUAXgLQAXgLAegBQAZABATAHQASAJALAPQAKAPAAAUQAAAKgDALQgCAKgIAMQgJAMgPAOIg0AyIBhAAIAAAqgAbOCMIAAi2IgtAAIAAgpIBhAAIAADfgAVcCMIAAhTQAAgWgKgKQgLgLgTAAQgWAAgMAMQgNANAAAYIAABNIgbAAIAAiUIAaAAIAAAWQAIgMAOgFQAOgGARAAQATAAANAHQAOAFAIAPQAIAPAAAVIAABWgAPFCMIAAiUIAaAAIAAAYQAHgNAOgFQANgHAUAAIAAAZIgDAAIgDAAQgWgBgMANQgNANAAAYIAABLgAHDCMIAAiUIAbAAIAACUgAqNCMIAAiUIAaAAIAAAYQAHgNANgFQAOgHAUAAIAAAZIgEAAIgDAAQgWgBgMANQgMANAAAYIAABLgAuFCMIAAhTQAAgWgKgKQgKgLgTAAQgUAAgMAMQgMANAAAYIAABNIgbAAIAAhTQAAgWgKgKQgKgLgSAAQgVAAgMAMQgMANAAAYIAABNIgbAAIAAiUIAaAAIAAAWQAIgMANgFQANgGARAAQARAAAOAHQANAFAIAOQAIgMAPgHQAPgHATAAQASAAAOAHQANAFAIAPQAIAPAAAVIAABWgEAjaAAIQgOgIgIgQQgIgRgBgYQABgYAIgRQAIgQAOgKQAOgIASAAQASAAAOAIQAOAKAIAQQAIARAAAYQAAAYgIARQgIAQgOAIQgOAKgSgBQgSABgOgKgEAjlgBcQgHAKAAAZQAAAZAHALQAIALANAAQANAAAHgLQAIgLAAgZQAAgZgIgKQgHgMgNAAIgBAAQgMAAgIAMgEggtgAGQgPgJgJgTQgJgTAAgaQAAgaAJgUQAJgSAPgKQAQgJAUAAQAUAAAPAJQAQAKAJASQAJAUAAAaQAAAagJATQgJATgQAJQgPAJgUAAQgUAAgQgJgEggggB2QgIAMgBAbQABAcAIAMQAJAMAOAAQAOAAAIgMQAJgMAAgcQAAgbgJgMQgIgNgOAAQgOAAgJANgEgjXAAAIAAgXIA+g6QAHgHAEgFQADgGACgEIABgIQAAgKgHgFQgGgFgNAAQgKAAgJAEQgJAEgFAIIgcgSQAKgNAQgIQARgIAVAAQASAAAOAGQANAFAIALQAHALAAAOQAAAIgCAIQgCAIgGAIQgFAJgMAKIglAjIBGAAIAAAdgEgkXAAAIAAiBIggAAIAAgfIBFAAIAACggASRgdIgZgWIgaAWIgZAAIAmglIAZAAIAmAlgAJngdIgagWIgZAWIgZAAIAlglIAaAAIAlAlgAg8gdIAmglIAhAAIguAlgAHDgqQgFgEAAgIQAAgIAFgEQAFgFAIgBQAIAAAFAGQAFAEAAAIQAAAHgFAFQgFAGgIAAQgIAAgFgGgA+ghcQgKgHgFgMQgGgMAAgSQAAgRAGgMQAFgMAKgGQAKgHANAAQANAAALAHQAKAGAFAMQAGAMAAARQAAASgGAMQgFAMgKAHQgLAGgNAAQgNAAgKgGgA+XimQgGAIAAARQAAATAGAHQAFAJAJgBQAKABAFgJQAGgHAAgTQAAgRgGgIQgFgIgKAAQgJAAgFAIg");
	this.shape.setTransform(-0.425,1.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-238.6,-26,474.2,47);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EA07AWjQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBjAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgEAyaAWjQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgEAv6AWjQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBkAAQAFAAACADQADADABAEQgBAEgDADQgCADgFAAgEAtbAWjQgFAAgCgDQgDgDgBgEQABgEADgDQACgDAFAAIBkAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgEAq7AWjQgFAAgCgDQgDgDAAgEQAAgEADgDQACgDAFAAIBkAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgEAobAWjQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBjAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgEAl6AWjQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgEAjaAWjQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBlAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgEAg7AWjQgFAAgCgDQgDgDAAgEQAAgEADgDQACgDAFAAIBkAAQAEAAADADQACADABAEQgBAEgCADQgDADgEAAgAebWjQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBkAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgAb6WjQgEAAgDgDQgCgDAAgEQAAgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgAZaWjQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBkAAQAFAAACADQADADABAEQgBAEgDADQgCADgFAAgAW7WjQgFAAgCgDQgDgDgBgEQABgEADgDQACgDAFAAIBkAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgAUbWjQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBkAAQAEAAADADQACADABAEQgBAEgCADQgDADgEAAgAR6WjQgEAAgDgDQgCgDAAgEQAAgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgAPaWjQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgAM6WjQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBlAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgAKbWjQgFAAgCgDQgDgDAAgEQAAgEADgDQACgDAFAAIBkAAQAEAAADADQACADABAEQgBAEgCADQgDADgEAAgAH7WjQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBjAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgAFaWjQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgAC6WjQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBkAAQAFAAACADQADADABAEQgBAEgDADQgCADgFAAgAAbWjQgFAAgCgDQgDgDgBgEQABgEADgDQACgDAFAAIBkAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgAiEWjQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBkAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgAklWjQgEAAgDgDQgCgDAAgEQAAgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgAnFWjQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgAplWjQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBlAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgAsEWjQgFAAgCgDQgDgDAAgEQAAgEADgDQACgDAFAAIBkAAQAEAAADADQACADABAEQgBAEgCADQgDADgEAAgAukWjQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBjAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgAxFWjQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgAzlWjQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBkAAQAFAAACADQADADABAEQgBAEgDADQgCADgFAAgA2EWjQgFAAgCgDQgDgDgBgEQABgEADgDQACgDAFAAIBkAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgA4kWjQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBkAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgA7FWjQgEAAgDgDQgCgDAAgEQAAgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgA9lWjQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgEggFAWjQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBlAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgEgikAWjQgFAAgCgDQgDgDAAgEQAAgEADgDQACgDAFAAIBkAAQAEAAADADQACADABAEQgBAEgCADQgDADgEAAgEglEAWjQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBjAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgEgnlAWjQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgEgqFAWjQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBkAAQAFAAACADQADADABAEQgBAEgDADQgCADgFAAgEgskAWjQgFAAgCgDQgDgDgBgEQABgEADgDQACgDAFAAIBkAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgEgvEAWjQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBkAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgEgxlAWjQgEAAgDgDQgCgDAAgEQAAgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgEg0FAWjQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgEg2lAWjQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBlAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgEA2yAV/QgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AAV4QgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2yATfQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AATYQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2yAQ/QgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AAQ4QgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2yAOfQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AAOYQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2yAL/QgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AAL4QgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2yAJfQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AAJYQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2yAG/QgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AAG4QgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2yAEfQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AAEYQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2yAB/QgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AAB4QgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2ygAgQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AgAnQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2ygDAQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AgDHQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2ygFgQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AgFnQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2ygIAQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AgIHQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2ygKgQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AgKnQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2ygNAQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AgNHQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2ygPgQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AgPnQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2ygSAQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AgSHQgCgDgBgEIAAhkQABgEACgDQADgDAEAAQAFAAACADQADADAAAEIAABkQAAAEgDADQgCADgFAAQgEAAgDgDgEA2ygUgQgCgDAAgEIAAhkQAAgEACgDQADgDAFAAQAEAAADADQACADAAAEIAABkQAAAEgCADQgDADgEAAQgFAAgDgDgEg3AgUnQgCgDgBgEIAAhkIABgDIgBgDQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAIhaAAIAABgQAAAEgDADQgCADgFAAQgEAAgDgDgEA0ngWOQgFAAgCgDQgDgDAAgEQAAgEADgDQACgDAFAAIBkAAQAEAAADADQACADABAEQgBAEgCADQgDADgEAAgEAyHgWOQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBjAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgEAvmgWOQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgEAtGgWOQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBkAAQAFAAACADQADADABAEQgBAEgDADQgCADgFAAgEAqngWOQgFAAgCgDQgDgDgBgEQABgEADgDQACgDAFAAIBkAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgEAoHgWOQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBkAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgEAlngWOQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBjAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgEAjGgWOQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgEAgmgWOQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBlAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgAeH2OQgFAAgCgDQgDgDAAgEQAAgEADgDQACgDAFAAIBkAAQAEAAADADQACADABAEQgBAEgCADQgDADgEAAgAbn2OQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBkAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgAZG2OQgEAAgDgDQgCgDAAgEQAAgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgAWm2OQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBkAAQAFAAACADQADADABAEQgBAEgDADQgCADgFAAgAUH2OQgFAAgCgDQgDgDgBgEQABgEADgDQACgDAFAAIBkAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgARn2OQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBkAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgAPG2OQgEAAgDgDQgCgDAAgEQAAgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgAMm2OQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgAKG2OQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBlAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgAHn2OQgFAAgCgDQgDgDAAgEQAAgEADgDQACgDAFAAIBkAAQAEAAADADQACADABAEQgBAEgCADQgDADgEAAgAFH2OQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBjAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgACm2OQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgAAG2OQgEAAgCgDQgCgDgBgEQABgEACgDQACgDAEAAIBkAAQAFAAACADQADADABAEQgBAEgDADQgCADgFAAgAiY2OQgFAAgCgDQgDgDgBgEQABgEADgDQACgDAFAAIBkAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgAk42OQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBkAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgAnZ2OQgEAAgDgDQgCgDAAgEQAAgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgAp52OQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgAsZ2OQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBlAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgAu42OQgFAAgCgDQgDgDAAgEQAAgEADgDQACgDAFAAIBkAAQAEAAADADQACADABAEQgBAEgCADQgDADgEAAgAxY2OQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBjAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgAz52OQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgA2Z2OQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBkAAQAFAAACADQADADABAEQgBAEgDADQgCADgFAAgA442OQgFAAgCgDQgDgDgBgEQABgEADgDQACgDAFAAIBkAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgA7Y2OQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBkAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgA952OQgEAAgDgDQgCgDAAgEQAAgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgEggZgWOQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgEgi5gWOQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBlAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgEglYgWOQgFAAgCgDQgDgDAAgEQAAgEADgDQACgDAFAAIBkAAQAEAAADADQACADABAEQgBAEgCADQgDADgEAAgEgn4gWOQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBjAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAgEgqZgWOQgEAAgDgDQgCgDgBgEQABgEACgDQADgDAEAAIBkAAQAFAAACADQADADAAAEQAAAEgDADQgCADgFAAgEgs5gWOQgEAAgCgDQgDgDgBgEQABgEADgDQACgDAEAAIBkAAQAFAAACADQADADABAEQgBAEgDADQgCADgFAAgEgvYgWOQgFAAgCgDQgDgDgBgEQABgEADgDQACgDAFAAIBkAAQAEAAACADQADADABAEQgBAEgDADQgCADgEAAgEgx4gWOQgFAAgDgDQgCgDAAgEQAAgEACgDQADgDAFAAIBkAAQAEAAADADQACADAAAEQAAAEgCADQgDADgEAAgEg0ZgWOQgEAAgDgDQgCgDAAgEQAAgEACgDQADgDAEAAIBkAAQAFAAADADQACADAAAEQAAAEgCADQgDADgFAAg");
	this.shape.setTransform(-9.35,-11.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(2,1,1).p("EBCuge/ICqA/EBE0ga8IAkjEEA3jgW5IN1nHEBDtAfAICpg/EBFyAa9IAkDEEA4iAW6IN0HHEhDsge/IipA/Eg4hgW5It0nHEhFxga8IgkjEEhCtAfAIiqg/EhEzAa9IgkDEEg3iAW6It1HH");
	this.shape_1.setTransform(-5.15,-12.35);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-456.3,-211.7,902.4000000000001,398.7);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol5("synched",0);
	this.instance.setTransform(192.65,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_1
	this.instance_1 = new lib.s1_goc();
	this.instance_1.setTransform(-77,-10);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77,-18.1,505.3,44.1);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.s1_khungphone();
	this.instance.setTransform(-506,-246);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(49).to({_off:true},1).wait(50));

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EhEzAjuQilAAh1h2Qh2h1ABilMAAAg67QgBilB2h2QB1h1ClAAMCJnAAAQClAAB1B1QB1B2AAClMAAAA67QAAClh1B1Qh1B2ilAAg");
	var mask_graphics_49 = new cjs.Graphics().p("EhEzAjuQilAAh1h2Qh2h1ABilMAAAg67QgBilB2h2QB1h1ClAAMCJnAAAQClAAB1B1QB1B2AAClMAAAA67QAAClh1B1Qh1B2ilAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-8.9,y:-1.775}).wait(49).to({graphics:mask_graphics_49,x:-8.9,y:-1.775}).wait(1).to({graphics:null,x:0,y:0}).wait(50));

	// Layer_5
	this.instance_1 = new lib.Symbol4("synched",0);
	this.instance_1.setTransform(-18.5,-187.6,1,1,0,0,0,175.6,3.9);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(19).to({_off:false},0).to({alpha:1},5).wait(25).to({startPosition:0},0).to({_off:true},1).wait(50));

	// Layer_4
	this.instance_2 = new lib.Symbol3("synched",0);
	this.instance_2.setTransform(-4.05,0,0.2216,0.2216);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(16).to({_off:false},0).to({scaleX:1.0425,scaleY:1.0425,y:10},8).to({scaleX:0.9762,scaleY:0.9762,x:-4.1,y:10.05},5).wait(20).to({startPosition:0},0).to({_off:true},1).wait(50));

	// Layer_3
	this.instance_3 = new lib.s1_ui();
	this.instance_3.setTransform(-652,-316);

	this.instance_4 = new lib.Tween1("synched",0);
	this.instance_4.setTransform(-2,0);
	this.instance_4._off = true;

	this.instance_5 = new lib.Tween2("synched",0);
	this.instance_5.setTransform(-2,0,0.7754,0.7754);

	var maskedShapeInstanceList = [this.instance_3,this.instance_4,this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3}]}).to({state:[{t:this.instance_4}]},9).to({state:[{t:this.instance_5}]},7).to({state:[{t:this.instance_5}]},33).to({state:[]},1).wait(50));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({_off:false},0).to({_off:true,scaleX:0.7754,scaleY:0.7754},7).wait(84));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-506,-246,1012,492);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_49 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(49).call(this.frame_49).wait(1));

	// Layer_1
	this.instance = new lib.Symbol2("synched",0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(50));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-506,-246,1012,492);


// stage content:
(lib._1012x492 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol1();
	this.instance.setTransform(506,246);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(360,176,794,386);
// library properties:
lib.properties = {
	id: 'DB9AD0C633893B48A18AD1592CC59CF8',
	width: 1012,
	height: 492,
	fps: 25,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"/images/star-3/s1_goc.png?1593491016636", id:"s1_goc"},
		{src:"/images/star-3/s1_khungphone.png?1593491016636", id:"s1_khungphone"},
		{src:"/images/star-3/s1_ui.jpg?1593491016636", id:"s1_ui"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.StageGL();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['DB9AD0C633893B48A18AD1592CC59CF8'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;